version: "3.9"
services:
  php: 
    build: public
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html


  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'boogle'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  
    
